// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztfacqwmzcyvezwtihyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0ZmFjcXdtemN5dmV6d3RpaHlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzU0MDksImV4cCI6MjA2MjExMTQwOX0.nj8a5MBkwLN8XNCR9nzwUl_ZdtOAA28g3L5pt43TRq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);